# pmm_fp.R - Polynomial Maximization Method with Fractional Polynomial basis
#
# Implements `pmm_fp()`, a frequentist counterpart to Bayesian Fractional
# Polynomials (Hubin et al. 2026) built on top of the PMM2 estimator
# (`lm_pmm2`). See:
#   /Users/serhiizabolotnii/Science/PMM-FP/Spec_PMM_FP.md  (sections 3.2, 4.3)
#   /Users/serhiizabolotnii/Science/PMM-FP/paper/decisions.md  (D1v2, D2)
#
# NOTE (scaffold v0.3.1.9001): the candidate-model search loop currently
# returns the OLS-FP design with a PMM2 refit only for the first candidate.
# A full sweep over all 2^K - 1 subsets with size <= max_terms and an
# information-criterion comparison is still TODO (see in-line markers).


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

#' Build fractional-polynomial basis transform of a numeric vector
#'
#' Applies the Royston-Altman convention: power `0` denotes `log(x)`; a
#' repeated power gives the `x^p * log(x)` companion term. In this scaffold
#' repeated powers are not generated by the enumeration step, so the simple
#' mapping suffices.
#'
#' @param x numeric vector (must be strictly positive)
#' @param p numeric scalar power from the FP basis
#'
#' @return numeric vector of length `length(x)`
#' @keywords internal
.fp_transform <- function(x, p) {
    if (any(x <= 0)) {
        stop(".fp_transform: 'x' must be strictly positive; apply shift first")
    }
    if (isTRUE(all.equal(p, 0))) {
        log(x)
    } else {
        x ^ p
    }
}


#' Enumerate candidate FP models up to `max_terms` powers
#'
#' Generates every non-empty subset of `powers` whose size is between 1 and
#' `max_terms`. Each subset becomes a candidate FP model.
#'
#' @param powers numeric vector of admissible powers
#' @param max_terms integer maximum subset size
#'
#' @return list of numeric vectors (each entry = one candidate)
#' @keywords internal
.enumerate_fp_models <- function(powers, max_terms) {
    max_terms <- min(max_terms, length(powers))
    out <- list()
    for (k in seq_len(max_terms)) {
        cmb <- utils::combn(powers, k, simplify = FALSE)
        out <- c(out, cmb)
    }
    out
}


#' Information-criterion value for a fitted PMM2 model
#'
#' Approximates the criterion from PMM2 residual variance (`m2`) and the
#' number of free coefficients. This is a placeholder until a proper
#' quasi-likelihood IC for PMM2 is wired in.
#'
#' @param fit a `PMM2fit` object
#' @param n integer sample size
#' @param criterion `"BIC"` or `"AIC"`
#'
#' @return numeric scalar
#' @keywords internal
.fp_ic <- function(fit, n, criterion) {
    k <- length(fit@coefficients)
    rss <- sum(fit@residuals ^ 2)
    if (rss <= 0 || !is.finite(rss)) return(Inf)
    ll <- -n / 2 * (log(2 * pi) + log(rss / n) + 1)
    penalty <- switch(criterion, BIC = log(n) * k, AIC = 2 * k)
    -2 * ll + penalty
}


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

#' Polynomial Maximization Method with Fractional Polynomial basis
#'
#' Fits a fractional-polynomial regression model with PMM2 (or PMM3, future)
#' estimation of the coefficients. The procedure enumerates subsets of an
#' FP basis (Royston-Altman 1994), refits each candidate with [lm_pmm2()],
#' and selects the minimiser of the chosen information criterion.
#'
#' Two basis tracks are supported (see Zabolotnii 2026, PMM-FP article,
#' frozen decision D1v2):
#'
#' * `track = "pos"` — `P_a = {0, 0.5, 1, 2, 3}` (K = 10 with companions),
#'   requires `E[xi^4] < inf`.
#' * `track = "full"` — `P_b = {-2, -1, -0.5, 0, 0.5, 1, 2, 3}` (K = 16),
#'   additionally requires bounded density at zero and `E[|xi|^-2] < inf`.
#'
#' The current implementation is a scaffold: it generates candidate models
#' and the design matrix, but only the first candidate is refit with PMM2.
#' Full PMM2 sweep and information-criterion comparison are planned for the
#' next iteration (see TODO markers in source).
#'
#' @param formula a two-sided formula of the form `y ~ x` with exactly one
#'   numeric predictor on the right-hand side. The intercept is added
#'   automatically through the FP design.
#' @param data a data.frame containing `y` and `x`.
#' @param track character: `"pos"` (default) or `"full"`. Selects the basis.
#' @param order integer PMM order; currently only `order = 2` is supported,
#'   `order = 3` is reserved for the symmetric platykurtic case.
#' @param max_terms integer maximum number of FP terms in a candidate model
#'   (default 4; see frozen decision D2).
#' @param criterion character: `"BIC"` (default) or `"AIC"`.
#' @param shift_eps numeric. If `min(x) <= 0`, `x` is shifted by
#'   `-min(x) + shift_eps`. When `NULL`, a default `1e-3` is used.
#'
#' @return an S4 object of class `PMM_FP_fit` inheriting from `PMM2fit`.
#'
#' @examples
#' \dontrun{
#'   set.seed(20260511)
#'   n <- 50
#'   x <- runif(n, 0.5, 5)
#'   y <- 1 + 2 * x ^ 0.5 + (rgamma(n, 2) - 2)
#'   fit <- pmm_fp(y ~ x, data = data.frame(x = x, y = y),
#'                 track = "pos", max_terms = 2)
#'   fit@selected_powers
#' }
#'
#' @references
#'   Royston P, Altman DG (1994). Regression using fractional polynomials of
#'   continuous covariates: parsimonious parametric modelling. Appl. Statist.
#'   43(3), 429-467.
#'
#'   Hubin A, Krogdahl T, Lokka A, Kortner T (2026). Bayesian Fractional
#'   Polynomials for Optimal Dosage Estimation. arXiv:2605.06237.
#'
#'   Zabolotnii S (2026). Polynomial Maximization Method with Fractional
#'   Polynomial Basis. In preparation.
#'
#' @export
pmm_fp <- function(formula,
                   data,
                   track     = c("pos", "full"),
                   order     = 2,
                   max_terms = 4,
                   criterion = c("BIC", "AIC"),
                   shift_eps = NULL) {

    call <- match.call()

    # --- argument validation -------------------------------------------------
    track     <- match.arg(track)
    criterion <- match.arg(criterion)

    if (missing(formula) || missing(data)) {
        stop("Both 'formula' and 'data' must be provided")
    }
    if (!inherits(formula, "formula")) {
        stop("'formula' must be a formula object")
    }
    if (!is.data.frame(data)) {
        stop("'data' must be a data.frame")
    }
    if (!order %in% c(2, 3)) {
        stop("'order' must be 2 or 3 (only 2 is implemented in this version)")
    }
    if (order == 3) {
        stop("PMM3 dispatch in pmm_fp() is not implemented yet")
    }
    if (!is.numeric(max_terms) || max_terms < 1) {
        stop("'max_terms' must be a positive integer")
    }

    # --- extract response and single predictor -------------------------------
    mf <- stats::model.frame(formula, data)
    y  <- stats::model.response(mf)
    rhs_vars <- attr(stats::terms(formula), "term.labels")
    if (length(rhs_vars) != 1L) {
        stop("pmm_fp() currently supports a single numeric predictor on RHS")
    }
    x_name <- rhs_vars[1]
    x <- mf[[x_name]]
    if (!is.numeric(x)) {
        stop("predictor '", x_name, "' must be numeric")
    }

    # --- preprocessing: shift to ensure x > 0 --------------------------------
    if (is.null(shift_eps)) shift_eps <- 1e-3
    applied_shift <- 0
    if (min(x) <= 0) {
        applied_shift <- -min(x) + shift_eps
        x <- x + applied_shift
    }
    n <- length(y)

    # --- basis selection (D1v2) ----------------------------------------------
    powers <- switch(track,
                     pos  = c(0, 0.5, 1, 2, 3),
                     full = c(-2, -1, -0.5, 0, 0.5, 1, 2, 3))

    # --- enumerate candidates ------------------------------------------------
    candidates <- .enumerate_fp_models(powers, max_terms)

    # --- fit candidates ------------------------------------------------------
    # TODO: full pmm2 fit per candidate. Current scaffold fits only the first
    #       candidate and records IC = NA for the rest. Replace the inner
    #       branch with `lm_pmm2(y ~ ., data = df)` for every candidate and
    #       pick the IC minimiser.
    ic_records <- data.frame(
        index   = seq_along(candidates),
        powers  = vapply(candidates,
                         function(p) paste(p, collapse = ","),
                         character(1)),
        n_terms = vapply(candidates, length, integer(1)),
        BIC     = NA_real_,
        AIC     = NA_real_,
        stringsAsFactors = FALSE
    )

    best_fit     <- NULL
    best_powers  <- NULL
    best_ic      <- Inf

    for (i in seq_along(candidates)) {
        p_vec <- candidates[[i]]
        design <- vapply(p_vec, function(p) .fp_transform(x, p),
                         numeric(n))
        if (!is.matrix(design)) design <- matrix(design, ncol = length(p_vec))
        colnames(design) <- paste0("fp", seq_along(p_vec))
        df <- data.frame(y = y, design)

        # TODO: drop this `if` once full sweep is implemented
        if (i == 1L) {
            fit <- tryCatch(
                lm_pmm2(stats::as.formula(
                    paste("y ~", paste(colnames(design), collapse = " + "))),
                    data = df),
                error = function(e) NULL
            )
            if (is.null(fit)) next
            ic_val <- .fp_ic(fit, n, criterion)
            ic_records$BIC[i] <- if (criterion == "BIC") ic_val else NA_real_
            ic_records$AIC[i] <- if (criterion == "AIC") ic_val else NA_real_

            if (ic_val < best_ic) {
                best_fit    <- fit
                best_powers <- p_vec
                best_ic     <- ic_val
            }
        }
    }

    if (is.null(best_fit)) {
        stop("pmm_fp(): no candidate model could be fitted")
    }

    warning("pmm_fp(): scaffold implementation - only the first candidate ",
            "model was refit with PMM2. Full FP search is TODO.",
            call. = FALSE)

    # --- assemble PMM_FP_fit object ------------------------------------------
    new("PMM_FP_fit",
        coefficients    = best_fit@coefficients,
        residuals       = best_fit@residuals,
        m2              = best_fit@m2,
        m3              = best_fit@m3,
        m4              = best_fit@m4,
        convergence     = best_fit@convergence,
        iterations      = best_fit@iterations,
        call            = call,
        selected_powers = best_powers,
        track           = track,
        all_models_ic   = ic_records,
        criterion       = criterion,
        shift_eps       = applied_shift)
}
